/* The Pinstripe Post — "On this day in Yankees history" moments.
   Each entry: m (month 1-12), d (day), y (year), title, text. */
window.PP_HISTORY = [
  { m: 1, d: 3, y: 1973, title: "The Boss arrives", text: "A group led by George Steinbrenner buys the Yankees from CBS for about $10 million. Over the next 37 years under his ownership, the Yankees win seven World Series titles." },
  { m: 1, d: 5, y: 1920, title: "Babe Ruth becomes a Yankee", text: "The Yankees announce they've bought Babe Ruth from the Red Sox. Ruth hits 54 home runs in his first season in New York, nearly doubling his own record of 29." },
  { m: 2, d: 6, y: 1895, title: "The Babe is born", text: "George Herman \"Babe\" Ruth is born in Baltimore. He'd go on to hit 659 of his 714 career home runs as a Yankee." },
  { m: 3, d: 8, y: 1999, title: "Farewell to the Yankee Clipper", text: "Joe DiMaggio dies at 84. The three-time MVP won nine World Series titles in 13 seasons and still holds the record with a 56-game hitting streak." },
  { m: 4, d: 16, y: 2009, title: "The new Yankee Stadium opens", text: "The Yankees play their first regular-season game at the new Yankee Stadium, across 161st Street from the original. They'd celebrate a World Series title there that November." },
  { m: 4, d: 18, y: 1923, title: "The House That Ruth Built opens", text: "Yankee Stadium opens in the Bronx in front of a huge crowd. Fittingly, Babe Ruth christens it with a three-run homer as the Yankees beat the Red Sox 4-1." },
  { m: 4, d: 26, y: 1992, title: "Aaron Judge is born", text: "Aaron Judge is born in Linden, California. He'd become the Yankees' captain and set the American League single-season home run record." },
  { m: 5, d: 2, y: 1939, title: "The streak ends", text: "Lou Gehrig takes himself out of the lineup in Detroit, ending his streak at 2,130 consecutive games. Weeks later he's diagnosed with ALS." },
  { m: 5, d: 12, y: 1925, title: "Yogi Berra is born", text: "Lawrence Peter \"Yogi\" Berra is born in St. Louis. The Hall of Fame catcher won 10 World Series rings, the most of any player." },
  { m: 5, d: 14, y: 1996, title: "Doc Gooden's no-hitter", text: "In his first season with the Yankees, Dwight Gooden no-hits the Seattle Mariners at Yankee Stadium." },
  { m: 5, d: 15, y: 1941, title: "The 56 begins", text: "Joe DiMaggio singles against the White Sox. Nobody knows it yet, but it's Game 1 of his record 56-game hitting streak." },
  { m: 5, d: 17, y: 1998, title: "David Wells is perfect", text: "David Wells throws a perfect game against the Minnesota Twins at Yankee Stadium: 27 up, 27 down, on Beanie Baby Day." },
  { m: 5, d: 19, y: 2021, title: "Kluber's no-hitter", text: "Corey Kluber no-hits the Texas Rangers in Arlington, the Yankees' first no-hitter since David Cone's perfect game in 1999." },
  { m: 6, d: 1, y: 1925, title: "The Iron Horse starts rolling", text: "Lou Gehrig pinch-hits for Pee Wee Wanninger. It's the first game of his 2,130-game streak, a record that stood for 56 years." },
  { m: 6, d: 2, y: 1941, title: "Lou Gehrig dies", text: "Lou Gehrig dies of ALS at 37, two years after retiring. The disease is still widely known as Lou Gehrig's disease." },
  { m: 6, d: 3, y: 1932, title: "Gehrig hits four", text: "Lou Gehrig becomes the first American League player to hit four home runs in one game, against the Athletics in Philadelphia." },
  { m: 6, d: 8, y: 1969, title: "Mickey Mantle Day", text: "The Yankees retire Mickey Mantle's No. 7 in front of a packed Yankee Stadium on Mickey Mantle Day." },
  { m: 6, d: 13, y: 1948, title: "The Babe bows out", text: "A very ill Babe Ruth makes his final appearance at Yankee Stadium for its 25th anniversary, and the Yankees retire his No. 3. The photo of him from behind won a Pulitzer Prize." },
  { m: 6, d: 19, y: 1903, title: "Lou Gehrig is born", text: "Henry Louis Gehrig is born in Manhattan. The Iron Horse would become one of the greatest first basemen ever." },
  { m: 6, d: 26, y: 1974, title: "Derek Jeter is born", text: "Derek Jeter is born in Pequannock, New Jersey. The Captain would collect 3,465 hits and five World Series rings, all as a Yankee." },
  { m: 6, d: 28, y: 2023, title: "Germán's perfect game", text: "Domingo Germán throws a perfect game in Oakland, the fourth perfect game in Yankees history." },
  { m: 7, d: 1, y: 2004, title: "Jeter dives into the stands", text: "Derek Jeter sprints after a pop-up and dives headfirst into the stands against the Red Sox, coming up bloodied but holding the ball. The Yankees win in 13 innings." },
  { m: 7, d: 4, y: 1939, title: "The Luckiest Man", text: "On Lou Gehrig Appreciation Day, the dying Gehrig tells a full Yankee Stadium: \"Today I consider myself the luckiest man on the face of the earth.\" His No. 4 became the first number retired in baseball." },
  { m: 7, d: 4, y: 1983, title: "Righetti's Fourth of July no-hitter", text: "Dave Righetti no-hits the Red Sox at Yankee Stadium on Independence Day, finishing it by striking out Wade Boggs." },
  { m: 7, d: 9, y: 2011, title: "Jeter's 3,000th hit", text: "Derek Jeter reaches 3,000 hits with a home run off David Price. He goes 5-for-5 and drives in the winning run." },
  { m: 7, d: 17, y: 1941, title: "The streak stops at 56", text: "Cleveland's pitchers and third baseman Ken Keltner's backhanded stops finally end Joe DiMaggio's 56-game hitting streak. He starts a new 16-game streak the next day." },
  { m: 7, d: 18, y: 1999, title: "David Cone is perfect", text: "On Yogi Berra Day, with Don Larsen throwing the ceremonial first pitch to Yogi, David Cone throws a perfect game against the Montreal Expos." },
  { m: 7, d: 24, y: 1983, title: "The Pine Tar Game", text: "George Brett's go-ahead homer for Kansas City is wiped out because of too much pine tar on his bat, and Brett storms out of the dugout. The ruling was later overturned." },
  { m: 8, d: 2, y: 1979, title: "Thurman Munson dies", text: "Yankees captain Thurman Munson dies in a plane crash at 32. The Yankees retire his No. 15, and his locker at the Stadium stayed empty." },
  { m: 8, d: 4, y: 2007, title: "A-Rod's 500th", text: "Alex Rodriguez hits his 500th career home run at Yankee Stadium, becoming the youngest player to reach 500 at the time." },
  { m: 8, d: 13, y: 1995, title: "Mickey Mantle dies", text: "Mickey Mantle dies at 63. The switch-hitter won three MVPs, seven World Series titles, and the Triple Crown in 1956." },
  { m: 8, d: 16, y: 1948, title: "Babe Ruth dies", text: "Babe Ruth dies at 53. His body lies in state at Yankee Stadium, where tens of thousands of fans line up to pay their respects." },
  { m: 9, d: 4, y: 1993, title: "Jim Abbott's no-hitter", text: "Jim Abbott, born without a right hand, no-hits Cleveland at Yankee Stadium. It's one of the most inspiring games in baseball history." },
  { m: 9, d: 19, y: 2011, title: "Mo becomes the saves king", text: "Mariano Rivera records his 602nd save, passing Trevor Hoffman for the most in history. He finishes his career with 652." },
  { m: 9, d: 21, y: 2008, title: "Goodbye, old Yankee Stadium", text: "The Yankees play the final game at the original Yankee Stadium, beating the Orioles. Derek Jeter thanks the fans from the field afterward." },
  { m: 9, d: 22, y: 2015, title: "Yogi Berra dies", text: "Yogi Berra dies at 90, exactly 69 years after his major league debut. \"It ain't over till it's over.\"" },
  { m: 9, d: 25, y: 2014, title: "Jeter's walk-off goodbye", text: "In his final game at Yankee Stadium, Derek Jeter wins it with a walk-off single to right against the Orioles." },
  { m: 9, d: 26, y: 2013, title: "Mo's last trip from the bullpen", text: "Derek Jeter and Andy Pettitte walk to the mound to take Mariano Rivera out of his final home game, and Rivera breaks down in tears." },
  { m: 9, d: 28, y: 2022, title: "Judge ties Maris", text: "Aaron Judge hits his 61st home run in Toronto, tying Roger Maris's American League and Yankees record." },
  { m: 9, d: 30, y: 1927, title: "Ruth hits 60", text: "Babe Ruth hits his 60th home run of the season off Tom Zachary, setting a record that stood for 34 years." },
  { m: 10, d: 1, y: 1932, title: "The Called Shot", text: "In World Series Game 3 at Wrigley Field, Babe Ruth gestures toward center field, then homers there off Charlie Root. Whether he really called it is still argued about." },
  { m: 10, d: 1, y: 1961, title: "Maris hits 61", text: "On the last day of the season, Roger Maris hits his 61st home run off Tracy Stallard, breaking Babe Ruth's single-season record." },
  { m: 10, d: 2, y: 1978, title: "Bucky Dent's home run", text: "In a one-game playoff at Fenway Park, light-hitting shortstop Bucky Dent lifts a three-run homer over the Green Monster. The Yankees win the division and later the World Series." },
  { m: 10, d: 4, y: 2022, title: "Judge hits 62", text: "On the final night of the regular season, Aaron Judge hits his 62nd home run in Texas, setting the American League record." },
  { m: 10, d: 5, y: 1953, title: "Five in a row", text: "Billy Martin's walk-off single in Game 6 beats the Brooklyn Dodgers and gives the Yankees their fifth straight World Series title, a record that still stands." },
  { m: 10, d: 8, y: 1956, title: "Don Larsen's perfect game", text: "Don Larsen throws the only perfect game in World Series history, beating the Brooklyn Dodgers in Game 5. Yogi Berra leaps into his arms." },
  { m: 10, d: 9, y: 1996, title: "The Jeffrey Maier game", text: "In ALCS Game 1, 12-year-old Jeffrey Maier reaches over the right-field wall and pulls in Derek Jeter's fly ball. It's ruled a home run, and Bernie Williams wins it in the 11th." },
  { m: 10, d: 13, y: 2001, title: "The Flip", text: "Facing elimination in Oakland, Derek Jeter races across the field, grabs an overthrow, and backhands it to Jorge Posada to nail Jeremy Giambi at the plate. The Yankees win 1-0." },
  { m: 10, d: 14, y: 1976, title: "Chambliss sends them to the Series", text: "Chris Chambliss hits a walk-off home run in ALCS Game 5 against Kansas City, sending the Yankees to their first World Series in 12 years as fans flood the field." },
  { m: 10, d: 15, y: 1923, title: "The first championship", text: "The Yankees beat the New York Giants in Game 6 to win their first World Series, in the first season at Yankee Stadium." },
  { m: 10, d: 16, y: 1962, title: "Richardson snags it", text: "In Game 7 against the Giants, second baseman Bobby Richardson catches Willie McCovey's line drive for the final out of a 1-0 win and a World Series title." },
  { m: 10, d: 16, y: 2003, title: "Aaron Boone's home run", text: "In ALCS Game 7 against the Red Sox, the Yankees rally against Pedro Martínez, and Aaron Boone ends it with a home run off Tim Wakefield in the 11th inning." },
  { m: 10, d: 17, y: 1978, title: "Back-to-back champions", text: "The Yankees beat the Dodgers in Game 6 to win their second straight World Series, finishing a comeback season that started 14 games behind Boston." },
  { m: 10, d: 18, y: 1977, title: "Mr. October", text: "Reggie Jackson hits three home runs on three straight pitches in World Series Game 6 against the Dodgers, clinching the Yankees' first title in 15 years." },
  { m: 10, d: 19, y: 2024, title: "Soto sends them to the World Series", text: "Juan Soto hits a three-run homer in the 10th inning of ALCS Game 5 in Cleveland, sending the Yankees to their first World Series since 2009." },
  { m: 10, d: 20, y: 1931, title: "Mickey Mantle is born", text: "Mickey Charles Mantle is born in Spavinaw, Oklahoma. He'd hit 536 home runs, including a record 18 in the World Series." },
  { m: 10, d: 21, y: 1998, title: "A historic team finishes the job", text: "The Yankees sweep the Padres to win the World Series, capping a 125-win season (counting the postseason), one of the best in baseball history." },
  { m: 10, d: 26, y: 1996, title: "A title at last", text: "The Yankees beat the Braves in Game 6 to win their first World Series in 18 years, and Wade Boggs takes a victory lap on a police horse." },
  { m: 10, d: 26, y: 2000, title: "The Subway Series", text: "The Yankees beat the Mets in Game 5 at Shea Stadium to win their third straight World Series and fourth in five years." },
  { m: 10, d: 27, y: 1999, title: "Sweeping the century", text: "The Yankees sweep the Braves to win the last World Series of the 1900s, their 25th championship." },
  { m: 11, d: 1, y: 2001, title: "Mr. November", text: "Just after midnight, with the World Series moving into November for the first time, Derek Jeter hits a walk-off home run against Arizona in Game 4, weeks after the 9/11 attacks." },
  { m: 11, d: 4, y: 2009, title: "Title No. 27", text: "The Yankees beat the Phillies in Game 6 to win their 27th World Series, the first in the new Yankee Stadium. Hideki Matsui drives in six runs and is named MVP." },
  { m: 11, d: 25, y: 1914, title: "Joe DiMaggio is born", text: "Joseph Paul DiMaggio is born in Martinez, California. The Yankee Clipper would win three MVPs and nine World Series titles." },
  { m: 11, d: 29, y: 1969, title: "Mariano Rivera is born", text: "Mariano Rivera is born in Panama City, Panama. In 2019 he became the first player elected unanimously to the Hall of Fame." },
  { m: 12, d: 21, y: 2022, title: "Judge named captain", text: "Aaron Judge is named the 16th captain in Yankees history, the first since Derek Jeter, as he officially signs a nine-year contract to stay in the Bronx." },
];
